# Generated by Django 6.0.6 on 2026-07-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_lesson_amount_remove_lesson_amount_url'),
        ('users', '0004_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=10, verbose_name='цена курса')),
                ('amount_url', models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату')),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_amount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
            },
        ),
    ]
