# Generated by Django 6.0.6 on 2026-07-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_amount_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount_lesson',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
        migrations.RenameField(
            model_name='amount_lesson',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='amount_lesson',
            name='amount',
        ),
    ]
