# Generated by Django 6.0.6 on 2026-06-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='сourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сourse', to='materials.course'),
        ),
    ]
