# Generated by Django 6.0.6 on 2026-06-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_сourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='сourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сour', to='materials.course'),
        ),
    ]
