# Generated by Django 6.0.6 on 2026-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_lesson_owner_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=10, verbose_name='цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
