# Generated by Django 6.0.6 on 2026-07-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_lesson_amount_lesson_amount_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='amount_url',
        ),
    ]
