# Generated by Django 6.0.6 on 2026-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_lesson_amount_remove_lesson_amount_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=10, verbose_name='цена курса'),
        ),
    ]
